apiVersion: v1
kind: Secret
metadata:
  name: civicissue-secrets
  namespace: civicissue
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  JWT_SECRET: Y2l2aWNpc3N1ZS1qd3Qtc2VjcmV0LWtleS0yMDI0LXByb2R1Y3Rpb24tZ3JhZGUtbWluaW11bS0yNTYtYml0cw==
